version: "3.8"
services:
  node1:
    build: .
    container_name: cluster-node1
    hostname: node1
    volumes:
      - ./docker/cluster.yaml:/app/cluster.yaml
    ports:
      - "8081:8080"
      - "7947:7946"
    networks:
      - cluster-net

  node2:
    build: .
    container_name: cluster-node2
    hostname: node2
    volumes:
      - ./docker/cluster2.yaml:/app/cluster.yaml
    ports:
      - "8082:8080"
      - "7948:7946"
    networks:
      - cluster-net

  node3:
    build: .
    container_name: cluster-node3
    hostname: node3
    volumes:
      - ./docker/cluster3.yaml:/app/cluster.yaml
    ports:
      - "8083:8080"
      - "7949:7946"
    networks:
      - cluster-net

networks:
  cluster-net:
    driver: bridge
