cluster:
  name: docker-cluster
  discovery_port: 7946
  bind_address: 0.0.0.0
  web_address: 0.0.0.0:8080
  enable_operator: true

backend:
  type: zookeeper
  namespace: "gocluster"
  
  zk_hosts:
    - "localhost:2181"
  zk_timeout: "30s"
  zk_session_path: "/gocluster/sessions"

nodes:
  node001: localhost:7946

plugins:
  - hello
  - jobs
